<?php /* NOTE: GENERATED BY GULP */ $default_theme_fonts = array(





'special_heading_1' => array(
  'font_family' => 'font_1_light', // font_family
  'font_style_name' => 'Special Heading 1',
  'font_size' => 30,
  'word_spacing' => 0,
  'letter_spacing' => 0.2,
  'line_height' => $generic_line_height,
  'default' => array(
      'font_color' => $color_black,
      'font_accent' => array(
          'bold' => 0,
          'italic' => 0,
          'underline' => 0,
      ),
      'font_case' => 'none', //'none','uppercase','lowercase'

  ),
  'hover_state' => array(
    ),
  'active' => array(
  ),
),

'heading_1' => array(
  'font_family' => 'font_2_italic', // font_family
  'font_style_name' => 'Heading 1',
  'font_size' => 30,
  'font_size_mobile' => 16,
  'word_spacing' => 0,
  'letter_spacing' => 0,
  'line_height' => $generic_line_height,
  'default' => array(
      'font_color' => $color_black,
      'font_accent' => array(
          'bold' => 0,
          'italic' => 0,
          'underline' => 0,
      ),
      'font_case' => 'none', //'none','uppercase','lowercase'

  ),
  'hover_state' => array(
    ),
  'active' => array(
  ),
),
'heading_2' => array(
  'font_family' => 'font_2_regular', // font_family
  'font_style_name' => 'Heading 2',
  'font_size' => 24,
  'word_spacing' => 0,
  'letter_spacing' => 0.22,
  'line_height' => 1.7,
  'default' => array(
      'font_color' => $color_black,
      'font_accent' => array(
          'bold' => 0,
          'italic' => 0,
          'underline' => 0,
      ),
      'font_case' => 'none', //'none','uppercase','lowercase'

  ),
  'hover_state' => array(
    ),
  'active' => array(
  ),
),
'heading_3' => array(
  'font_family' => 'font_1_light', // font_family
  'font_style_name' => 'Heading 3',
  'font_size' => 47,
  'font_size_mobile' => 26,
  'word_spacing' => 0,
  'letter_spacing' => 0.2,
  'line_height' => $generic_line_height,
  'default' => array(
      'font_color' => $color_black,
      'font_accent' => array(
          'bold' => 0,
          'italic' => 0,
          'underline' => 0,
      ),
      'font_case' => 'none', //'none','uppercase','lowercase'

  ),
  'hover_state' => array(
    ),
  'active' => array(
  ),
),
'heading_4' => array(
  'font_family' => 'font_1_bold', // font_family
  'font_style_name' => 'Heading 4',
  'font_size' => 32,
  'word_spacing' => 0,
  'letter_spacing' => 0,
  'line_height' => $generic_line_height,
  'default' => array(
      'font_color' => $color_black,
      'font_accent' => array(
          'bold' => 0,
          'italic' => 0,
          'underline' => 0,
      ),
      'font_case' => 'none', //'none','uppercase','lowercase'

  ),
  'hover_state' => array(
    ),
  'active' => array(
  ),
),

'label_1' => array(
  'font_family' => 'font_1_regular', // font_family
  'font_style_name' => 'Label 1',
  'font_size' => 9,
  'word_spacing' => 0,
  'letter_spacing' => 0.3,
  'line_height' => 2,
  'default' => array(
      'font_color' => $color_black,
      'font_accent' => array(
          'bold' => 0,
          'italic' => 0,
          'underline' => 0,
      ),
      'font_case' => 'none', //'none','uppercase','lowercase'

  ),
  'hover_state' => array(
    ),
  'active' => array(
  ),
),
'label_2' => array(
  'font_family' => 'font_1_bold', // font_family
  'font_style_name' => 'Label 2',
  'font_size' => 10,
  'word_spacing' => 0,
  'letter_spacing' => 0.3,
  'line_height' => 3,
  'default' => array(
      'font_color' => $color_black,
      'font_accent' => array(
          'bold' => 0,
          'italic' => 0,
          'underline' => 0,
      ),
      'font_case' => 'none', //'none','uppercase','lowercase'

  ),
  'hover_state' => array(
    ),
  'active' => array(
    'font_color' => $color_gray_dark,
    'font_accent' => array(
          'bold' => 0,
          'italic' => 0,
          'underline' => 0,
      ),
    'font_case' => 'none', //'none','uppercase','lowercase'
  ),
),
'label_3' => array(
  'font_family' => 'font_1_bold', // font_family
  'font_style_name' => 'Label 3',
  'font_size' => 12,
  'word_spacing' => 0,
  'letter_spacing' => 0.25,
  //'line_height' => $generic_letter_spacing,
  'line_height' => 1.45,
  'default' => array(
      'font_color' => $color_black,
      'font_accent' => array(
          'bold' => 0,
          'italic' => 0,
          'underline' => 0,
      ),
      'font_case' => 'none', //'none','uppercase','lowercase'

  ),
  'hover_state' => array(
    ),
  'active' => array(
  ),
),
'label_4' => array(
  'font_family' => 'font_2_regular', // font_family
  'font_style_name' => 'Label 4',
  'font_size' => 17,
  'word_spacing' => 0,
  'letter_spacing' => 0,
  'line_height' => $generic_line_height,
  'default' => array(
      'font_color' => $color_black,
      'font_accent' => array(
          'bold' => 0,
          'italic' => 0,
          'underline' => 0,
      ),
      'font_case' => 'none', //'none','uppercase','lowercase'

  ),
  'hover_state' => array(
    ),
  'active' => array(
    'font_color' => '#808080',
    'font_accent' => array(
          'bold' => 0,
          'italic' => 0,
          'underline' => 0,
      ),
    'font_case' => 'none', //'none','uppercase','lowercase'
  ),
),
'label_5' => array(
  'font_family' => 'font_2_italic', // font_family
  'font_style_name' => 'Label 5',
  'font_size' => 14,
  'word_spacing' => 0,
  'letter_spacing' => 0,
  'line_height' => 1.59,
  'default' => array(
      'font_color' => $color_black,
      'font_accent' => array(
          'bold' => 0,
          'italic' => 0,
          'underline' => 0,
      ),
      'font_case' => 'none', //'none','uppercase','lowercase'

  ),
  'hover_state' => array(
    ),
  'active' => array(
  ),
),

'paragraph_1' => array(
  'font_family' => 'font_2_regular', // font_family
  'font_style_name' => 'Paragraph 1',
  'font_size' => 15,
  'word_spacing' => 0,
  'letter_spacing' => 0,
  'line_height' => 2.35,
  'default' => array(
      'font_color' => $color_black,
      'font_accent' => array(
          'bold' => 0,
          'italic' => 0,
          'underline' => 0,
      ),
      'font_case' => 'none', //'none','uppercase','lowercase'

  ),
  'hover_state' => array(
    ),
  'active' => array(
  ),
),

'paragraph_2' => array(
  'font_family' => 'font_2_regular', // font_family
  'font_style_name' => 'Paragraph 2',
  'font_size' => 15,
  'word_spacing' => 0,
  'letter_spacing' => 0,
  'line_height' => 2.35,
  'default' => array(
      'font_color' => $color_gray_dark,
      'font_accent' => array(
          'bold' => 0,
          'italic' => 0,
          'underline' => 0,
      ),
      'font_case' => 'none', //'none','uppercase','lowercase'

  ),
  'hover_state' => array(
    ),
  'active' => array(
  ),
),

/* START: CONTENT TYPOGRAPHY */

  'h1' => array(
    'font_family' => 'font_1_light', // font_family
    'font_style_name' => 'H1',
    'font_size' => 47,
    'font_size_mobile' => 37,
    'word_spacing' => 0,
    'letter_spacing' => 0.2,
    'line_height' => $generic_line_height,
    'default' => array(
        'font_color' => $color_black,
        'font_accent' => array(
            'bold' => 0,
            'italic' => 0,
            'underline' => 0,
        ),
        'font_case' => 'none', //'none','uppercase','lowercase'

    ),
    'hover_state' => array(
      ),
    'active' => array(
    ),
  ),
  'h2' => array(
    'font_family' => 'font_1_light', // font_family
    'font_style_name' => 'H2',
    'font_size' => 36,
    'font_size_mobile' => 26,
    'word_spacing' => 0,
    'letter_spacing' => 0.2,
    'line_height' => $generic_line_height,
    'default' => array(
        'font_color' => $color_black,
        'font_accent' => array(
            'bold' => 0,
            'italic' => 0,
            'underline' => 0,
        ),
        'font_case' => 'none', //'none','uppercase','lowercase'

    ),
    'hover_state' => array(
      ),
    'active' => array(
    ),
  ),
  'h3' => array(
    'font_family' => 'font_1_light', // font_family
    'font_style_name' => 'H3',
    'font_size' => 28,
    'font_size_mobile' => 20,
    'word_spacing' => 0,
    'letter_spacing' => 0.2,
    'line_height' => $generic_line_height,
    'default' => array(
        'font_color' => $color_black,
        'font_accent' => array(
            'bold' => 0,
            'italic' => 0,
            'underline' => 0,
        ),
        'font_case' => 'none', //'none','uppercase','lowercase'

    ),
    'hover_state' => array(
      ),
    'active' => array(
    ),
  ),
  'h4' => array(
    'font_family' => 'font_1_light', // font_family
    'font_style_name' => 'H4',
    'font_size' => 23,
    'font_size_mobile' => 18,
    'word_spacing' => 0,
    'letter_spacing' => 0.2,
    'line_height' => $generic_line_height,
    'default' => array(
        'font_color' => $color_black,
        'font_accent' => array(
            'bold' => 0,
            'italic' => 0,
            'underline' => 0,
        ),
        'font_case' => 'none', //'none','uppercase','lowercase'

    ),
    'hover_state' => array(
      ),
    'active' => array(
    ),
  ),
  'h5' => array(
    'font_family' => 'font_1_light', // font_family
    'font_style_name' => 'H5',
    'font_size' => 20,
    'font_size_mobile' => 16,
    'word_spacing' => 0,
    'letter_spacing' => 0.2,
    'line_height' => $generic_line_height,
    'default' => array(
        'font_color' => $color_black,
        'font_accent' => array(
            'bold' => 0,
            'italic' => 0,
            'underline' => 0,
        ),
        'font_case' => 'none', //'none','uppercase','lowercase'

    ),
    'hover_state' => array(
      ),
    'active' => array(
    ),
  ),
  'h6' => array(
    'font_family' => 'font_1_light', // font_family
    'font_style_name' => 'H6',
    'font_size' => 18,
    'font_size_mobile' => 14,
    'word_spacing' => 0,
    'letter_spacing' => 0.2,
    'line_height' => $generic_line_height,
    'default' => array(
        'font_color' => $color_black,
        'font_accent' => array(
            'bold' => 0,
            'italic' => 0,
            'underline' => 0,
        ),
        'font_case' => 'none', //'none','uppercase','lowercase'

    ),
    'hover_state' => array(
      ),
    'active' => array(
    ),
  ),

  // Blockquote -> Heading 1

/* END: CONTENT TYPOGRAPHY */


); ?>