{{-- NOTE: GENERATED BY GULP !!! --}}<div class="flo-mobile-menu flo-mobile-menu--full-height flo-mobile-menu--top flo-mobile-menu--search">
    <div class="flo-mobile-menu__title">Search</div>

    <div class="flo-mobile-menu__search-form">
        {{ get_search_form() }}
    </div>

    <span class="flo-mobile-menu__close flo-icon-cancel"></span>
</div>
