{{-- NOTE: GENERATED BY GULP !!! --}}@extends("layout.block")
@section('block_content')
  <div class="flo-wp-title flo-post">
    <h1 class="flo-wp-title__title">{{ the_title() }}</h1>
  </div>
@overwrite
